### ISSUE TITLE
options not available on android ?

### ISSUE THREAD

**Issue by alec6** [photokandyStudios/PKVideoThumbnail#11]
Hi,

The plugin works well until i put options.
This code works perfectly
`        window.PKVideoThumbnail.createThumbnail (entry.nativeURL, name + '.png',function(prevSucc) {
          return prevImageSuccess(prevSucc);
        }, fail);`

This code does not work.
`        window.PKVideoThumbnail.createThumbnail (entry.nativeURL, name + '.png', {resize: {width: 512, height: 384}} ,function(prevSucc) {
          return prevImageSuccess(prevSucc);
        }, fail);`

Maybe, i made a mistake.

Regards

**Comment by kerrishotts** [comment]
Are you using version 2.x of the plugin?

Can you post any error messages you might be getting? (If you can, see what adb logcat generates as well)

Also, what version of Android are you testing on?

**Comment by alec6** [comment]
Ouh la
I'm feeling stupid.
I used a version 1.x.
After an update, it woks well :+1:
