### ISSUE TITLE
No result from  window.PKVideoThumbnail.createThumbnail  function call

### ISSUE THREAD

**Issue by sagarhiremath6** [photokandyStudios/PKVideoThumbnail#13]
Hello,

I am working Phone gap project in which I am displaying video thumbnail to users after they upload video files. But I see neither the success result nor the error message.

I have installed plugin by following command as specified in doc and it got installed also.
`cordova plugin add cordova-plugin-photokandy-video-thumbnail --save`

I am using latest version of plugin. My question is do we need any configuration in config.xml? or is it issue with my code?

`var sourceVideoPath = "file:///"+device_local_path;
  var targetThumbnailPath = cordova.file.dataDirectory + "demo.PNG";
  window.PKVideoThumbnail.createThumbnail ( sourceVideoPath, targetThumbnailPath, thumbnailsuccess, thumbnailfailure );`

I tried to write both external memory and internal memory, But no use. Can you please help us with this?

And does it work with Phonegap Desktop app or Do we need to test on actual devices using executable files? In this scenario I tried both. But did not work out.

**Comment by kerrishotts** [comment]
The plugin will not work with the Desktop/Developer app -- you need to test either on an emulator or a physical device using an actual build (either from PhoneGap Build or the Cordova/PG CLI). 

It might help to see any JavaScript and device logs. Also, what device(s) and operating system version(s) are you testing on?

**Comment by kerrishotts** [comment]
Also -- put an alert or console log before and after the call to createThumbnail. Do you see both, or just the first?

**Comment by sagarhiremath6** [comment]
Thanks a lot for quick response. This is how I am testing. All coding is being done in Jaavascript and then I am getting apk file from Phonegap Build. And then i am testing on actual android device Redmi version number 4.4.4. My way of testing app is correct in order to use video thumbnail plugin?

**Comment by kerrishotts** [comment]
Please see my two previous comments -- any logs (JavaScript and Device) you have would be nice to see; otherwise I'm not sure how much I can help. Also, try to put alert()/console.log before and after the createThumbnail call to verify that execution is getting through. Also, please share your config.xml file.

Finally, you might just try using "cdvfile://localhost/persistent/" paths, since the plugin now works with those.

**Comment by sagarhiremath6** [comment]
I mad it worked. Thanks for all your help.  Just changed my video source path to
`sourceVideoPath = "file:/"+data;`
