### ISSUE TITLE
Cordova IOS warning

### ISSUE THREAD

**Issue by pcrombach** [photokandyStudios/PKVideoThumbnail#3]
PKVideoThumbnail.m:77:40: 'toSuccessCallbackString:' is deprecated: Deprecated in Cordova 3.6. Use the CDVCommandDelegate method sendPluginResult:callbackId instead. This will be removed in 4.0.0

**Comment by kerrishotts** [comment]
Thanks for the heads up!

**Comment by eweap** [comment]
Hello, you have news about these changes? This seems to make the build fail now for iOS. Thanks !

**Comment by kerrishotts** [comment]
Hi @eweap -- I'm working on some much-needed changes in the v2.x branch; I've got a first pass up that should work for iOS, but it's not complete yet, and not fully tested. Android will be coming shortly.

Note that 2.x is a breaking change -- there is an options parameter (see the file in www/) now.

**Comment by eweap** [comment]
@kerrishotts It sounds great ! Thanks :)
