### ISSUE TITLE
Error: Failed to fetch plugin com.photokandy.videothumbnail via registry.

### ISSUE THREAD

**Issue by EriksonMurrugarra** [photokandyStudios/PKVideoThumbnail#7]
Hello, Everytime I try to execute this command:
`cordova plugin add com.photokandy.videothumbnail`

I am receiving the following error:

> Error: Failed to fetch plugin com.photokandy.videothumbnail via registry.
Probably this is either a connection problem, or plugin spec is incorrect.
Check your connection and plugin name/version/URL.
Error: Registry returned 404 for GET on https://registry.npmjs.org/com.photokand
y.videothumbnail

What could be the reason?
Thanks.

**Comment by AlphaNerds** [comment]
i get same

**Comment by kerrishotts** [comment]
Try using `cordova plugin add cordova-plugin-photokandy-video-thumbnail` instead. If that doesn't work, you can install from Git (`cordova plugin add https://github.com/photokandyStudios/PKVideoThumbnail`).

If you're feeling adventurous, you can try installing from the 2.x branch (`cordova plugin add https://github.com/photokandyStudios/PKVideoThumbnail#2.x`), but it's not fully tested yet, and has some breaking changes.

**Comment by AlphaNerds** [comment]
Yup, that did the trick. Thanks !!

**Comment by kerrishotts** [comment]
Just so you know, 2.x has been released. Let me know if you have any problems with it.
